created_at = "2026-09-21T11:23:14.512"
runtime_s = 17607.0350075
id = "3c903956-7701-4975-876e-894987507799"
source_file = "Re_CFT_TransLine_K20truncrank48_niter18_μ0-0.0237_λ0.01.jld2"

[[iterations]]
central_charge = 1.052887090462692
iteration = 0
notes = ""
sectors = []
[[iterations]]
central_charge = 0.7303827205385836
iteration = 1
notes = ""
sectors = []
[[iterations]]
central_charge = 0.8462838060384394
iteration = 2
notes = ""
sectors = []
[[iterations]]
central_charge = 0.7305895044786497
iteration = 3
notes = ""
sectors = []
[[iterations]]
central_charge = 0.728907140939909
iteration = 4
notes = ""
sectors = []
[[iterations]]
central_charge = 0.671198937214359
iteration = 5
notes = ""
sectors = []
[[iterations]]
central_charge = 0.6396525583627583
iteration = 6
notes = ""
sectors = []
[[iterations]]
central_charge = 0.5969436474686008
iteration = 7
notes = ""
sectors = []
[[iterations]]
central_charge = 0.564574587599445
iteration = 8
notes = ""
sectors = []
[[iterations]]
central_charge = 0.5354608992509258
iteration = 9
notes = ""
sectors = []
[[iterations]]
central_charge = 0.513742087849348
iteration = 10
notes = ""
sectors = []
[[iterations]]
central_charge = 0.49424414412487233
iteration = 11
notes = ""
sectors = []
[[iterations]]
central_charge = 0.4720851727983402
iteration = 12
notes = ""
sectors = []
[[iterations]]
central_charge = 0.43859314296386676
iteration = 13
notes = ""
sectors = []
[[iterations]]
central_charge = 0.3842519270397889
iteration = 14
notes = ""
sectors = []
[[iterations]]
central_charge = 0.3018112827430606
iteration = 15
notes = ""
sectors = []
[[iterations]]
central_charge = 0.19719025866875706
iteration = 16
notes = ""
sectors = []
[[iterations]]
central_charge = 0.09679607920985114
iteration = 17
notes = ""
sectors = []
[[iterations]]
central_charge = 0.03135013540345974
iteration = 18
notes = ""
sectors = []

[params]
chi = 48
symmetry = "Z2"
model = "phi4_real"
algorithm = "LoopTNR"
lambda = 0.01
mu0_sq = -0.0237
K = 20
