created_at = "2026-09-21T11:26:03.073"
runtime_s = 52939.134335331
id = "76a5c329-9120-4e46-9ee3-4b3a7cb8bbdc"
source_file = "Re_CFT_TransLine_K40truncrank48_niter18_μ0-0.0346_λ0.015.jld2"

[[iterations]]
central_charge = 1.0404028577150497
iteration = 0
notes = ""
sectors = []
[[iterations]]
central_charge = 0.7159441292506123
iteration = 1
notes = ""
sectors = []
[[iterations]]
central_charge = 0.8289427996740447
iteration = 2
notes = ""
sectors = []
[[iterations]]
central_charge = 0.712443441534636
iteration = 3
notes = ""
sectors = []
[[iterations]]
central_charge = 0.7095972911841788
iteration = 4
notes = ""
sectors = []
[[iterations]]
central_charge = 0.6522892293574717
iteration = 5
notes = ""
sectors = []
[[iterations]]
central_charge = 0.6217414738767569
iteration = 6
notes = ""
sectors = []
[[iterations]]
central_charge = 0.5818448795024105
iteration = 7
notes = ""
sectors = []
[[iterations]]
central_charge = 0.5537930254510284
iteration = 8
notes = ""
sectors = []
[[iterations]]
central_charge = 0.5308122824866321
iteration = 9
notes = ""
sectors = []
[[iterations]]
central_charge = 0.516958401528558
iteration = 10
notes = ""
sectors = []
[[iterations]]
central_charge = 0.5085271592214593
iteration = 11
notes = ""
sectors = []
[[iterations]]
central_charge = 0.5042019781064534
iteration = 12
notes = ""
sectors = []
[[iterations]]
central_charge = 0.5017683515460422
iteration = 13
notes = ""
sectors = []
[[iterations]]
central_charge = 0.5002996458988591
iteration = 14
notes = ""
sectors = []
[[iterations]]
central_charge = 0.49893509011411963
iteration = 15
notes = ""
sectors = []
[[iterations]]
central_charge = 0.49706925243154143
iteration = 16
notes = ""
sectors = []
[[iterations]]
central_charge = 0.49376593458469514
iteration = 17
notes = ""
sectors = []
[[iterations]]
central_charge = 0.4874517656555397
iteration = 18
notes = ""
sectors = []

[params]
chi = 48
symmetry = "Z2"
model = "phi4_real"
algorithm = "LoopTNR"
lambda = 0.015
mu0_sq = -0.0346
K = 40
