created_at = "2026-09-21T11:23:33.402"
runtime_s = 17486.04389516
id = "a95d17c1-da67-4f8d-a654-2a07589b635b"
source_file = "Re_CFT_TransLine_K20truncrank48_niter18_μ0-0.1843_λ0.1.jld2"

[[iterations]]
central_charge = 0.9456920424926478
iteration = 0
notes = ""
sectors = []
[[iterations]]
central_charge = 0.6250591484458498
iteration = 1
notes = ""
sectors = []
[[iterations]]
central_charge = 0.7240057906111755
iteration = 2
notes = ""
sectors = []
[[iterations]]
central_charge = 0.6096453838473385
iteration = 3
notes = ""
sectors = []
[[iterations]]
central_charge = 0.6045204191274937
iteration = 4
notes = ""
sectors = []
[[iterations]]
central_charge = 0.5567320495522564
iteration = 5
notes = ""
sectors = []
[[iterations]]
central_charge = 0.5393308393670173
iteration = 6
notes = ""
sectors = []
[[iterations]]
central_charge = 0.5193874416163493
iteration = 7
notes = ""
sectors = []
[[iterations]]
central_charge = 0.5112070216616639
iteration = 8
notes = ""
sectors = []
[[iterations]]
central_charge = 0.5051338297962381
iteration = 9
notes = ""
sectors = []
[[iterations]]
central_charge = 0.5028042504996166
iteration = 10
notes = ""
sectors = []
[[iterations]]
central_charge = 0.5012356744396683
iteration = 11
notes = ""
sectors = []
[[iterations]]
central_charge = 0.5006012950357415
iteration = 12
notes = ""
sectors = []
[[iterations]]
central_charge = 0.5001112925025071
iteration = 13
notes = ""
sectors = []
[[iterations]]
central_charge = 0.4997601395812665
iteration = 14
notes = ""
sectors = []
[[iterations]]
central_charge = 0.49925062889291255
iteration = 15
notes = ""
sectors = []
[[iterations]]
central_charge = 0.4983847133720619
iteration = 16
notes = ""
sectors = []
[[iterations]]
central_charge = 0.4967066551581477
iteration = 17
notes = ""
sectors = []
[[iterations]]
central_charge = 0.49341989928801827
iteration = 18
notes = ""
sectors = []

[params]
chi = 48
symmetry = "Z2"
model = "phi4_real"
algorithm = "LoopTNR"
lambda = 0.1
mu0_sq = -0.1843
K = 20
