created_at = "2026-09-21T11:23:41.452"
runtime_s = 19882.896705217
id = "ca37e962-76e6-4891-87b5-41f7978a4fa6"
source_file = "Re_CFT_TransLine_K20truncrank48_niter18_μ0-0.4034_λ0.25.jld2"

[[iterations]]
central_charge = 0.8912309854901584
iteration = 0
notes = ""
sectors = []
[[iterations]]
central_charge = 0.5784906291715096
iteration = 1
notes = ""
sectors = []
[[iterations]]
central_charge = 0.6711058082936835
iteration = 2
notes = ""
sectors = []
[[iterations]]
central_charge = 0.5642816385354179
iteration = 3
notes = ""
sectors = []
[[iterations]]
central_charge = 0.5638828473957881
iteration = 4
notes = ""
sectors = []
[[iterations]]
central_charge = 0.5270244223759913
iteration = 5
notes = ""
sectors = []
[[iterations]]
central_charge = 0.5192796901755501
iteration = 6
notes = ""
sectors = []
[[iterations]]
central_charge = 0.5077339397094062
iteration = 7
notes = ""
sectors = []
[[iterations]]
central_charge = 0.5048629342710526
iteration = 8
notes = ""
sectors = []
[[iterations]]
central_charge = 0.5017697241292791
iteration = 9
notes = ""
sectors = []
[[iterations]]
central_charge = 0.5008458874404946
iteration = 10
notes = ""
sectors = []
[[iterations]]
central_charge = 0.49971157118870385
iteration = 11
notes = ""
sectors = []
[[iterations]]
central_charge = 0.4987520568410072
iteration = 12
notes = ""
sectors = []
[[iterations]]
central_charge = 0.49701876536422784
iteration = 13
notes = ""
sectors = []
[[iterations]]
central_charge = 0.49390056804190136
iteration = 14
notes = ""
sectors = []
[[iterations]]
central_charge = 0.48778768340542006
iteration = 15
notes = ""
sectors = []
[[iterations]]
central_charge = 0.4759643769358621
iteration = 16
notes = ""
sectors = []
[[iterations]]
central_charge = 0.4535409910155574
iteration = 17
notes = ""
sectors = []
[[iterations]]
central_charge = 0.41304591538307683
iteration = 18
notes = ""
sectors = []

[params]
chi = 48
symmetry = "Z2"
model = "phi4_real"
algorithm = "LoopTNR"
lambda = 0.25
mu0_sq = -0.4034
K = 20
