created_at = "2026-09-21T11:23:55.550"
runtime_s = 16429.852038908
id = "d6504696-6f65-4fed-94b8-85908f67170f"
source_file = "Re_CFT_TransLine_K20truncrank48_niter18_μ0-0.7204_λ0.5.jld2"

[[iterations]]
central_charge = 0.847734768252527
iteration = 0
notes = ""
sectors = []
[[iterations]]
central_charge = 0.5447650993421971
iteration = 1
notes = ""
sectors = []
[[iterations]]
central_charge = 0.6341662491231558
iteration = 2
notes = ""
sectors = []
[[iterations]]
central_charge = 0.5364716670004961
iteration = 3
notes = ""
sectors = []
[[iterations]]
central_charge = 0.5418959105099294
iteration = 4
notes = ""
sectors = []
[[iterations]]
central_charge = 0.5132928128820473
iteration = 5
notes = ""
sectors = []
[[iterations]]
central_charge = 0.5111863941701754
iteration = 6
notes = ""
sectors = []
[[iterations]]
central_charge = 0.503452571418389
iteration = 7
notes = ""
sectors = []
[[iterations]]
central_charge = 0.5025986456858651
iteration = 8
notes = ""
sectors = []
[[iterations]]
central_charge = 0.5004749237525128
iteration = 9
notes = ""
sectors = []
[[iterations]]
central_charge = 0.49987320288301
iteration = 10
notes = ""
sectors = []
[[iterations]]
central_charge = 0.4985703959971586
iteration = 11
notes = ""
sectors = []
[[iterations]]
central_charge = 0.49687862637482605
iteration = 12
notes = ""
sectors = []
[[iterations]]
central_charge = 0.4934987805552195
iteration = 13
notes = ""
sectors = []
[[iterations]]
central_charge = 0.48705741896696503
iteration = 14
notes = ""
sectors = []
[[iterations]]
central_charge = 0.4745243764797599
iteration = 15
notes = ""
sectors = []
[[iterations]]
central_charge = 0.45087126655571413
iteration = 16
notes = ""
sectors = []
[[iterations]]
central_charge = 0.40838727893998716
iteration = 17
notes = ""
sectors = []
[[iterations]]
central_charge = 0.3389027051208658
iteration = 18
notes = ""
sectors = []

[params]
chi = 48
symmetry = "Z2"
model = "phi4_real"
algorithm = "LoopTNR"
lambda = 0.5
mu0_sq = -0.7204
K = 20
