created_at = "2026-09-21T11:26:07.515"
runtime_s = 54352.75321721
id = "e8255d97-2180-4934-8b94-ffcaef478a6f"
source_file = "Re_CFT_TransLine_K40truncrank48_niter18_μ0-0.0446_λ0.02.jld2"

[[iterations]]
central_charge = 1.027594003517374
iteration = 0
notes = ""
sectors = []
[[iterations]]
central_charge = 0.7028783669383121
iteration = 1
notes = ""
sectors = []
[[iterations]]
central_charge = 0.813729840690868
iteration = 2
notes = ""
sectors = []
[[iterations]]
central_charge = 0.6966554064424457
iteration = 3
notes = ""
sectors = []
[[iterations]]
central_charge = 0.6926552980033361
iteration = 4
notes = ""
sectors = []
[[iterations]]
central_charge = 0.6354460839546081
iteration = 5
notes = ""
sectors = []
[[iterations]]
central_charge = 0.6056115608735333
iteration = 6
notes = ""
sectors = []
[[iterations]]
central_charge = 0.5679373772349139
iteration = 7
notes = ""
sectors = []
[[iterations]]
central_charge = 0.5429758829225662
iteration = 8
notes = ""
sectors = []
[[iterations]]
central_charge = 0.5232775955861743
iteration = 9
notes = ""
sectors = []
[[iterations]]
central_charge = 0.5118401013105294
iteration = 10
notes = ""
sectors = []
[[iterations]]
central_charge = 0.5043857321050789
iteration = 11
notes = ""
sectors = []
[[iterations]]
central_charge = 0.49926860588181043
iteration = 12
notes = ""
sectors = []
[[iterations]]
central_charge = 0.4936591532551587
iteration = 13
notes = ""
sectors = []
[[iterations]]
central_charge = 0.48513114057159756
iteration = 14
notes = ""
sectors = []
[[iterations]]
central_charge = 0.4697532911196033
iteration = 15
notes = ""
sectors = []
[[iterations]]
central_charge = 0.44158018557868406
iteration = 16
notes = ""
sectors = []
[[iterations]]
central_charge = 0.3922560880977051
iteration = 17
notes = ""
sectors = []
[[iterations]]
central_charge = 0.31454975232066645
iteration = 18
notes = ""
sectors = []

[params]
chi = 48
symmetry = "Z2"
model = "phi4_real"
algorithm = "LoopTNR"
lambda = 0.02
mu0_sq = -0.0446
K = 40
