created_at = "2026-09-21T11:24:24.999"
runtime_s = 7332.40283427
id = "ebb49879-1754-4b34-9306-73917c3647af"
source_file = "Re_CFT_TransLine_K40truncrank32_niter18_μ0-0.0632_λ0.03.jld2"

[[iterations]]
central_charge = 1.0078458255534017
iteration = 0
notes = ""
sectors = []
[[iterations]]
central_charge = 0.6829073279677754
iteration = 1
notes = ""
sectors = []
[[iterations]]
central_charge = 0.7903459371016763
iteration = 2
notes = ""
sectors = []
[[iterations]]
central_charge = 0.6724795837513253
iteration = 3
notes = ""
sectors = []
[[iterations]]
central_charge = 0.66674045482774
iteration = 4
notes = ""
sectors = []
[[iterations]]
central_charge = 0.6101485525739917
iteration = 5
notes = ""
sectors = []
[[iterations]]
central_charge = 0.5817878311430248
iteration = 6
notes = ""
sectors = []
[[iterations]]
central_charge = 0.5472289059957645
iteration = 7
notes = ""
sectors = []
[[iterations]]
central_charge = 0.5251319917584336
iteration = 8
notes = ""
sectors = []
[[iterations]]
central_charge = 0.5057433872441522
iteration = 9
notes = ""
sectors = []
[[iterations]]
central_charge = 0.4889315128731383
iteration = 10
notes = ""
sectors = []
[[iterations]]
central_charge = 0.46651986616823354
iteration = 11
notes = ""
sectors = []
[[iterations]]
central_charge = 0.43119150125431216
iteration = 12
notes = ""
sectors = []
[[iterations]]
central_charge = 0.3729839499736886
iteration = 13
notes = ""
sectors = []
[[iterations]]
central_charge = 0.28634652717995174
iteration = 14
notes = ""
sectors = []
[[iterations]]
central_charge = 0.180214823085803
iteration = 15
notes = ""
sectors = []
[[iterations]]
central_charge = 0.08365818356871174
iteration = 16
notes = ""
sectors = []
[[iterations]]
central_charge = 0.02502647736714641
iteration = 17
notes = ""
sectors = []
[[iterations]]
central_charge = 0.00404259847273383
iteration = 18
notes = ""
sectors = []

[params]
chi = 32
symmetry = "Z2"
model = "phi4_real"
algorithm = "LoopTNR"
lambda = 0.03
mu0_sq = -0.0632
K = 40
